version: 2
project_name: cryptolens

before:
  hooks:
    - go mod tidy
    - windres versioninfo.rc -O coff -o versioninfo.syso

builds:
  - id: cryptolens
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/cryptolens
    binary: cryptolens
    dir: .
    ldflags:
      - "-s -w"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: abdorrahmani
    name: cryptolens
  draft: false
  prerelease: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  extra_files:
    - glob: LICENSE
    - glob: README.md
    - glob: CHANGELOG.md 
