# CryptoLens Configuration

# AES Encryption Settings
aes:
  defaultKeySize: 256  # Key size in bits (128, 192, or 256)
  keyFile: "aes_key.bin"  # File to store AES keys

# Base64 Settings
base64:
  paddingChar: "="  # Character used for padding

# Caesar Cipher Settings
caesar:
  defaultShift: 3  # Default shift value for Caesar cipher

# RSA Settings
rsa:
  keySize: 2048  # Key size in bits
  publicKeyFile: "rsa_public.pem"  # File to store public key
  privateKeyFile: "rsa_private.pem"  # File to store private key

# HMAC Settings
hmac:
  keySize: 256  # Key size in bits
  keyFile: "hmac_key.bin"  # File to store HMAC key
  hashAlgorithm: "sha256"  # Hash algorithm to use (sha1, sha256, sha512, blake2b-256, blake2b-512, blake3)
  availableAlgorithms:  # List of available hash algorithms
    - "sha1"
    - "sha256"
    - "sha512"
    - "blake2b-256"
    - "blake2b-512"
    - "blake3"

# General Settings
general:
  logLevel: "info"  # Log level (debug, info, warn, error)
  debug: false  # Enable debug mode 