# CryptoLens Configuration

# AES Encryption Settings
aes:
  defaultKeySize: 256  # Key size in bits (128, 192, or 256)
  keyFile: "aes_key.bin"  # File to store AES keys

# Base64 Settings
base64:
  paddingChar: "="  # Character used for padding

# Caesar Cipher Settings
caesar:
  defaultShift: 3  # Default shift value for Caesar cipher

# RSA Settings
rsa:
  keySize: 2048  # Key size in bits
  publicKeyFile: "rsa_public.pem"  # File to store public key
  privateKeyFile: "rsa_private.pem"  # File to store private key

# HMAC Settings
hmac:
  keySize: 256  # Key size in bits
  keyFile: "hmac_key.bin"  # File to store HMAC key
  hashAlgorithm: "sha256"  # Hash algorithm to use (sha1, sha256, sha512, blake2b-256, blake2b-512, blake3)
  availableAlgorithms:  # List of available hash algorithms
    - "sha1"
    - "sha256"
    - "sha512"
    - "blake2b-256"
    - "blake2b-512"
    - "blake3"

# PBKDF Settings
pbkdf:
  algorithm: "argon2id"  # Algorithm to use (pbkdf2, argon2id, scrypt)
  iterations: 3  # Number of iterations (for Argon2id, this is the time parameter)
  memory: 65536  # Memory usage in KB (for Argon2id, minimum 8KB)
  threads: 4  # Number of threads (for Argon2id, minimum 1)
  keyLength: 32  # Key length in bytes
  availableAlgorithms:  # List of available algorithms
    - "pbkdf2"
    - "argon2id"
    - "scrypt"

# Diffie-Hellman Settings
dh:
  keySize: 2048  # Key size in bits
  generator: 2  # Generator value (g)
  primeFile: "dh_prime.bin"  # File to store the prime number
  privateKeyFile: "dh_private.bin"  # File to store private key
  publicKeyFile: "dh_public.bin"  # File to store public key
  sharedSecretFile: "dh_shared.bin"  # File to store shared secret

# General Settings
general:
  logLevel: "info"  # Log level (debug, info, warn, error)
  debug: false  # Enable debug mode 